export const skills = [
  "HTML5",
  "CSS3",
  "JavaScript (ES6)",
  "TypeScript",
  "Next.js",
  "React.js",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Tailwind CSS",
  "Bootstrap",
  "Mongoose",
  "Material UI",
  "Firebase",
  "PlayWright",
  "JWT",
  "Shadcn UI",
];

export const experiences = [
  {
    id: 1,
    title: "React Developer",
    company: "Talentship Global Advisory",
    type: "Internship",
    duration: "2 Months",
    range: "Aug 21, 2023 - Oct 21, 2023",
    description:
      "This was my first internship after completing my course. I worked on two projects 6Sparks LLC and Unity Yoga Studio. I had become the team leader in the Unity Yoga Studio project.",
    certificate:
      "https://drive.google.com/file/d/1thUJXVkUA_gJULGPA8DKP_JXhoiwB2ix/view?usp=sharing",
  },
  {
    id: 2,
    title: "React Developer",
    company: "CEHPoint E-Learning & Ceyber Security",

    type: "Internship",
    duration: "2 Months",
    range: "Sep 10, 2023 - Nov 10, 2023",
    description:
      "I worked on the Thaiseva project. I have built an Admin Dashboard for the Thaiseva Application alone. I built the project with React and Firebase (Including Storage, Firestore, and Authentication).",
    certificate:
      "https://drive.google.com/file/d/18X-sKuKU07GlX-zgsHsaJvCMH4kGbVy8/view?usp=sharing",
  },
];

export const cardsData = [
  {
    id: 1,
    title: "Buy 100 Coins",
    description: "Buy 100 coins for just $1",
    price: 1,
    coins: 100,
  },
  {
    id: 2,
    title: "Buy 500 Coins",
    description: "Buy 500 coins for just $5",
    price: 5,
    coins: 500,
  },
  {
    id: 3,
    title: "Buy 1000 Coins",
    description: "Buy 1000 coins for just $10",
    price: 10,
    coins: 1000,
  },
];

export const recipeCategories = [
  "Appetizers & Snacks",
  "Main Courses",
  "Desserts & Sweets",
  "Salads & Sides",
  "Soups & Stews",
  "Breakfast & Brunch",
  "Beverages & Drinks",
  "Vegetarian & Vegan",
  "Meat & Poultry",
  "Seafood & Fish",
  "Pasta & Noodles",
  "Breads & Baking",
  "Healthy & Low-Calorie",
  "Quick & Easy",
  "International Cuisine",
  "Holiday & Special Occasions",
  "Gluten-Free",
  "Kid-Friendly",
  "Slow Cooker & Instant Pot",
  "Grilling & BBQ",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
